id: connect_to_redux_store
learningObjectives: 
- Managing state with Redux
hints:
- hinst
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Great job!"
        delay: 1000
      - text: "Now, it's time to manage the state of the selected items using Redux. This is an important step in the process, as it will allow us to keep track of which items have been selected and easily perform actions on them."
        delay: 2000
      - text: "To get started, please open up the Redux store and add the necessary actions, reducers, and selectors for managing the selected items. Make sure to test your implementation thoroughly and ensure that everything is working as expected."
        delay: 2000
      - text: "Open a PR when you're done"
        delay: 2000
githubActions:
  frontend:
    capabilities:
    - jest-puppeteer
    testFile: "items.test.js"
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch: 
      key: "${eventType}"
      cases: 
        github_pr_opened:
          do: 
            - actionId: bot_message
              params:
                person: keen
                messages:
                - text: On that was fast, I'll review the changes right away.     
                  delay: 1000
        github_pr_workflow_complete_success:
          do:
            - actionId: bot_message
              params: 
                person: keen
                message:
                - text: "Nailed it! Excellent job @${user.githubuser}! You can now merge the PR."
                delay: 2000
            - actionId: github_pr_approve
              params:
                person: keen
                message: "Nailed it! Excellent job @${user.githubuser}! You can now merge the PR."
        github_pr_workflow_complete_failure:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                - text: "Make sure your fix passes all the checks, then try again please."
                delay: 3000
            - actionId: github_pr_reject
              params:
                person: keen
                message: "Looks like this code change didn’t fix the problem. Can you take a second look?"
        github_pr_merged:
          do: 
            - actionId: finish_step
