id: integrate_backend_and_frontend
learningObjectives: 
- Integrate backend and frontend
- Component creation 
hints:
- hints
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: "Well done! we're making a great progress on this feature"
        delay: 1000
      - text: "As the next step, we need to create a button component that will trigger the deletion of the selected items. This button should be visible on the profile page and only appear when one or more items are selected."
        delay: 2000 
      - text: "Can you please create this button component? It should be styled in a way that makes it clear and prominent, and it should be functional so that it triggers the deletion of the selected items when clicked."
        delay: 2500
      - text: "Open a PR when you're done"
githubActions:
  frontend:
    capabilities:
    - jest-puppeteer
    testFile: "items.test.js"
trigger:
  type: github_pr_lifecycle_status
  flowNode:
    switch: 
      key: "${eventType}"
      cases: 
        github_pr_opened:
          do: 
            - actionId: bot_message
              params:
                person: keen
                messages:
                - text: On that was fast, I'll review the changes right away.     
                  delay: 1000
        github_pr_workflow_complete_success:
          do:
            - actionId: bot_message
              params: 
                person: keen
                message:
                - text: "Nailed it! Excellent job @${user.githubuser}! You can now merge the PR."
                delay: 2000
            - actionId: github_pr_approve
              params:
                person: keen
                message: "Nailed it! Excellent job @${user.githubuser}! You can now merge the PR."
        github_pr_workflow_complete_failure:
          do:
            - actionId: bot_message
              params:
                person: keen
                messages:
                - text: "Make sure your fix passes all the checks, then try again please."
                delay: 3000
            - actionId: github_pr_reject
              params:
                person: keen
                message: "Looks like this code change didn’t fix the problem. Can you take a second look?"
        github_pr_merged:
          do: 
            - actionId: finish_step
